---
busNodePort: 40002
dataNodePort: 30002

env:
  REDIS_CLUSTER_ANNOUNCE_PORT: "30002"
  REDIS_CLUSTER_BUS_ANNOUNCE_PORT: "40002"
  REDIS_CLUSTER_ANNOUNCE_IP: "192.168.59.121"
  REDIS_PORT_NUMBER: "30002"
  # REDIS_PORT_NUMBER: "6379"
