---
busNodePort: 40000
dataNodePort: 30000

env:
  REDIS_CLUSTER_ANNOUNCE_PORT: "30000"
  REDIS_CLUSTER_BUS_ANNOUNCE_PORT: "40000"
  REDIS_CLUSTER_ANNOUNCE_IP: "192.168.59.121"
  REDIS_PORT_NUMBER: "30000"
  # REDIS_PORT_NUMBER: "6379"
